# Generated by Django 4.2.19 on 2025-03-09 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='genre.collection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piece',
            name='year',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
