# Generated by Django 4.2.19 on 2025-03-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0002_piece_collection_piece_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='year',
            field=models.IntegerField(default=2000),
        ),
    ]
