# Generated by Django 4.2.21 on 2025-05-30 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0003_alter_piece_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='genre.piece')),
            ],
        ),
    ]
